# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:tienda_deportiva;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.port=8081

# Habilita la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desactiva JPA/Hibernate
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Ejecutar scripts al iniciar
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Configuración de vistas JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Configuración de recursos estáticos
spring.web.resources.static-locations=classpath:/static/